import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { getServerSession } from "next-auth";
import { options } from "./api/auth/[...nextauth]/options";
import "./globals.css";
import AuthProvider from "@/context/auth/session-provider";
import Sidebar from "@/components/sidebar";
import Header from "@/components/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type TProps = {
  children: React.ReactNode;
};

export default async function RootLayout({ children }: TProps) {
  const session = await getServerSession(options);
  const isLogIn = !!session?.user?.id;

  return (
    <html lang="en" className="h-full">
      <body className={`${inter.className} h-full bg-slate-700`}>
        <AuthProvider>
          <Header />
          {isLogIn && (
            <div className="grid grid-cols-1 md:grid-cols-8 lg:grid-cols-8 xl:grid-cols-8 gap-4">
              <div className="md:col-span-3 lg:col-span-3 xl:col-span-2">
                <Sidebar />
              </div>
              <div className="md:col-span-5 lg:col-span-5 xl:col-span-6">
                {children}
              </div>
            </div>
          )}
        </AuthProvider>
      </body>
    </html>
  );
}
